### ISSUE TITLE
[Feature Request] Show resource IDs in the UI

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-UI#135]
**Problem description**
Each resource has a unique ID associated with them, which is already part of the `ResourceType` interface. It would be useful to show them on pages that show details on the resource (e.g. the `collaboration.read.component` and other read components) - if a user then wants to use the resource in the Python client they know the ID.

**Desired solution**
Add field ID to each read component.

**Comment by richard-elastique** [comment]
Fixed with PR #151.
