### ISSUE TITLE
[Bug] When creating role, user can select roles that they cannot assign

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-UI#183]
**Describe the bug**
A user should only be able to assign permissions to other users that are same level or lower than they have themselves. This prevents that a regular user can create a new role with more permissions and thereby elevate their own permissions. 

This is currently not the case: see screenshots below, where a user can assign global permissions that they do not have themselves.

**Expected behavior**
In the create role component, a user can only tick boxes that they are allowed to assign

**Screenshots**
![image](https://github.com/vantage6/vantage6-UI/assets/10533678/e7af7a00-8bb2-4ddd-b8b7-2129c25c5ed2)
Top: which permissions the logged-in user (with role 'Collaboration admin') has
Bottom: which permissions they can assign

**Comment by eutj** [comment]
There is a bug in this bug report!
This is the correct screenshot when creating a role as collaboration admin:
![image](https://github.com/vantage6/vantage6-UI/assets/149147510/cfae90fb-a4d6-4c78-b959-5ab883fd69a5)

**Comment by bartvanb** [comment]
Cool :-)
I think it might have been an issue with logging in multiple times with different users that had different permissions, and this has probably been solved by https://github.com/vantage6/vantage6-UI/pull/196/commits/40b0f23b9f3c66cf2daf2a1222f6e81d946ec374
