### ISSUE TITLE
[Bug] Reloading or direct loading a subpath within the app leads to a 404

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6-UI#226]
**Describe the bug**

After interacting with the UI, a user might end up in a path like `vantage6-ui.example.org/collaborations`. If the user were to refresh/reload, they'd get a 404. This happens for any subpath, even `vantage6-ui.example.org/login`. 

It also happens if the user directly access a subpath, as in, opening `vantage6-ui.example.com/login` directly.

**To Reproduce**
1. Go to vantage6-ui.example.com/login
2. See 404

**Expected behavior**
Not getting a 404 and the subpath location being loaded.

**Details**
- Vantage6-ui 4.2.0 

**Additional context**

If a collaboration has just been created that collaboration will not show up immediately after under `/collaborations` (this is a separate issue). A way around this is to refresh/reload the page, but this produces a 404. To solve this the user has to go to the main domain for the ui vantage6-ui.example.org and navigate from there to collaborations again. I think the same might go for `/users`, etc.

This would be nice if a server admin wants to give instruction to a UI-user and sends them a link with a subpath.

**Comment by bartvanb** [comment]
This can be solved by adding a hashtag in the angular path which I did for the old UI [here](https://github.com/vantage6/vantage6-UI/commit/ee07d48f58bf572f1742afeb4e73342099bd7045). 

Not sure if we still need to release this for the old UI as beta for the new one is already available and old one will be phased out soon. What do you think @lsago

**Comment by bartvanb** [comment]
> Ah, nice. I ended up solving it [via a different way](https://angular.io/guide/deployment#routed-apps-must-fall-back-to-indexhtml:~:text=Nginx,.html%3B). I can push it to a branch for you to check out if you want, let me know.

I think unless someone really needs this we can leave it to save time. Seeing you already fixed it yourself I don't see a need to do so unless someone else also has this issue

> And I agree, if new UI will be released soon, we can just only have the fix in new version. Do you have an estimate when it will be officially released?

It depends on finishing up the algorithm store, for which authorization (in progress) and documentation (under review) still need to be finished. My estimate is a few weeks but no guarantees ;-)

**Comment by bartvanb** [comment]
Resolved in new UI (I think). Feel free to reopen if you disagree
