### ISSUE TITLE
[Bug] Column names are not selectable from the UI even though they are shared

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-UI#228]
**Describe the bug**
If I create a new average task through the UI it does not give me a dropdown in the **Define parameters** . Also when I create the task It does not pass the `column_name` to the task on the server. I do see the request to `/column` and I do see the correct column names are reported.

**Expected behavior**

**Screenshots**
![image](https://github.com/vantage6/vantage6-UI/assets/15981243/52761d60-3f1f-4b28-ae8f-51b1d298bd05)
![image](https://github.com/vantage6/vantage6-UI/assets/15981243/2aa7726d-97bd-4fc0-a9e4-3dd5a8062173)

**Details**
 - Version 4.3.0b3

**Comment by bartvanb** [comment]
Which process is used to share the columns? Is your node setup to share the columns on startup or is it achieved via calling the basics algorithm (this only happens if you refuse to share config in the node config file or if the database requires a query, workbook or other parameter)

**Comment by bartvanb** [comment]
This turned out to be caused by an error in the linked algorithm store: the argument type was `null` - a dropdown with column names is only shown if argument type is `column`
