### ISSUE TITLE
[Bug] Previous logged-in user username

### ISSUE THREAD

**Issue by anjavangestel** [vantage6/vantage6-UI#53]
**Describe the bug**
When you are logged in with user A, logout and login with user B: the username of user A is displayed on the right top user-button. Just for a few seconds, before it changes in the username of user B.

**To Reproduce**
1. Log in with user A.
2. Log out.
3. In the same browser, log in with user B.
4. See error: in the right top the username of user A is visible.

**Expected behavior**
Username of user B on the right top button.

**Details**
https://portal.petronas.vantage6.ai
UI version 3.3.7

**Comment by bartvanb** [comment]
Fixed in #50 (v3.3.7-post1)
