### ISSUE TITLE
[Bug] Wrong error message 'You cannot change your password here!' while adding permission rule

### ISSUE THREAD

**Issue by anjavangestel** [vantage6/vantage6-UI#54]
**Describe the bug**
When I edit a user's details I get the message 'You cannot change your password here!' while I didn't do anything to the password.

**To Reproduce**
1. Click on a user. (I used one with the roles Researcher and Organization Admin, it should probably be a different user than the user you are logged in with)
2. Click on 'Edit'.
3. Select the User/Own/View Role (or de-select if it is already added).
4. Click on 'Save'
5. See error: pop-up with 'You cannot change your password here!'

**Expected behavior**
No pop-up message.

**Details**
https://portal.petronas.vantage6.ai
UI version 3.3.7

**Comment by bartvanb** [comment]
Fixed in #51
