### ISSUE TITLE
[Bug] Email already exists, but still shown in UI

### ISSUE THREAD

**Issue by anjavangestel** [vantage6/vantage6-UI#55]
**Describe the bug**
When I edit the email address of user A and change it to the email address of user B, you'll get a pop-up message that this email is already in use, but still the email of user A is updated in the UI.

**To Reproduce**
1. Go to user A.
2. Click on 'Edit'.
3. Change 'Email' to email of user B.
4. Click on 'Save' --> Pop-up appears with 'User with that email already exists.'
5. Click on 'Close'.
6. Go to user A (to see details).
7. See error: 'Email' shows email of user B.

**Expected behavior**
Is assume it is not okay that two users have the same email.
So; the email of user A should not be updated.

**Details**
https://portal.petronas.vantage6.ai/
UI version 3.3.7

**Comment by frankcorneliusmartin** [comment]
Is the email still updated after you fresh the page?

**Comment by anjavangestel** [comment]
After refreshing the page the email field is empty.
