### ISSUE TITLE
[Change Request] Create/edit resources should be done via forms

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-UI#61]
**Description**
Currently, edit/create pages are simply tables with values that users have to fill in. Instead, we should use forms (probably those from Angular Material) which automatically give us many extras such as form validation. This prevents us having to build those checks manually, gives a better user experience and it alleviates maintenance on the long run (as extra checks are included more neatly).

**Comment by richard-elastique** [comment]
Done in the new UI.
